### ISSUE TITLE
Making forms fun again

### ISSUE THREAD

**Issue by leesheppard** [rubyaustralia/roro#168]
A 15 minute talk aimed at a general web programming experience level audience. 

Forms are everywhere. Some asking for simple login information and more complex multipage forms through to short surveys. Adding some illustrations or cartoons increases engagement as well as interpreting for audiences who may not speak the language form inputs have been written in.

A mix of CSS, Jquery and HTML5 with spritesheet concepts and some examples of discoveries in implementing visual elements to forms will be in this talk.

**Comment by paulfioravanti** [comment]
@leesheppard Did you have a particular month you'd prefer to do this talk? If June, then I'd probably say that since you presented last month, if no one else steps up with a full length talk, then sure. So, it might be worth preparing the materials for it, and we can at least initially put you on reserve. Does that sound fair?

**Comment by paulfioravanti** [comment]
@leesheppard You don't happen to want to give this talk at the October meetup, do you? 😸

**Comment by leesheppard** [comment]
Just flagging I have spoken with Paul and that I will give this talk, I'll update here when I can present to the group.
